export const Submission = [
    {
        id: 1,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Rejected",
        date: "May 15, 2025",
    },
    {
        id: 2,
        title: "Neural Network Visualizer",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Reviewed",
        date: "May 16, 2025",
    },
    {
        id: 3,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "4",
        team: "Tech Titans",
        status: "Pending",
        date: "May 17, 2025",
    },
    {
        id: 4,
        title: "Sustainable Energy Monitor",
        categoty: "AI Innovation challege",
        members: "5",
        team: "Code Warriors",
        status: "Rejected",
        date: "May 18, 2025",
    },
    {
        id: 5,
        title: "Voice Recognition API",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Reviewed",
        date: "May 19, 2025",
    },
    {
        id: 6,
        title: "AI-Powered Chatbot",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Pending",
        date: "May 20, 2025",
    },
    {
        id: 7,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "4",
        team: "Tech Titans",
        status: "Rejected",
        date: "May 21, 2025",
    },
    {
        id: 8,
        title: "Sustainable Energy Monitor",
        categoty: "AI Innovation challege",
        members: "5",
        team: "Code Warriors",
        status: "Reviewed",
        date: "May 22, 2025",
    },
    {
        id: 9,
        title: "Voice Recognition API",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Pending",
        date: "May 23, 2025",
    },
    {
        id: 10,
        title: "AI-Powered Chatbot",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Rejected",
        date: "May 24, 2025",
    },
    {
        id: 11,
        title: "Sustainable Energy Monitor",
        categoty: "AI Innovation challege",
        members: "5",
        team: "Code Warriors",
        status: "Reviewed",
        date: "May 22, 2025",
    },
    {
        id: 12,
        title: "Neural Network Visualizer",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Reviewed",
        date: "May 16, 2025",
    }, 
    {
        id: 13,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Rejected",
        date: "May 15, 2025",
    },
    {
        id: 14,
        title: "Voice Recognition API",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Pending",
        date: "May 23, 2025",
    },
    {
        id: 15,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "4",
        team: "Tech Titans",
        status: "Pending",
        date: "May 17, 2025",
    },

]

export const ParticipantsData = [
    {
        id: 1,
        title: "Jane Cooper",
        phone_no: "(225) 555-0118",
        email: "jane@microsoft.com",
        team: "Code Wizards",
        country: "United States",
        status: "Active"
    },
    {
        id: 2,
        title: "Floyd Miles",
        phone_no: "(205) 555-0100",
        email: "floyd@yahoo.com",
        team: "Byte Builders",
        country: "Kiribati",
        status: "Active"
    },
    {
        id: 3,
        title: "Ronald Richards",
        phone_no: "(302) 555-0107",
        email: "ronald@adobe.com",
        team: "Algo Masters",
        country: "Israel",
        status: "Inactive"
    },
    {
        id: 4,
        title: "Marvin McKinney",
        phone_no: "(252) 555-0126",
        email: "marvin@tesla.com",
        team: "Code Wizards",
        country: "Iran",
        status: "Inactive"
    },   
     {
        id: 5,
        title: "Jerome Bell",
        phone_no: "(629) 555-0129",
        email: "jerome@google.com",
        team: "Byte Builders",
        country: "Réunion",
        status: "Active"
    },
    {
        id: 6,
        title: "Kathryn Murphy",
        phone_no: "(406) 555-0120",
        email: "kathryn@microsoft.com",
        team: "Algo Masters",
        country: "Curaçao",
        status: "Inactive"
    },
    {
        id: 7,
        title: "Jacob Jones",
        phone_no: "(208) 555-0112",
        email: "jacob@yahoo.com",
        team: "Byte Builders",
        country: "Brazil",
        status: "Active"
    },
    {
        id: 8,
        title: "Kristin Watson",
        phone_no: "(252) 555-0126",
        email: "marvin@tesla.com",
        team: "Code Wizards",
        country: "Iran",
        status: "Inactive"
    },  
    {
        id: 9,
        title: "Jacob Jones",
        phone_no: "(208) 555-0112",
        email: "jacob@yahoo.com",
        team: "Byte Builders",
        country: "Brazil",
        status: "Active"
    },
    {
        id: 10,
        title: "Kristin Watson",
        phone_no: "(252) 555-0126",
        email: "marvin@tesla.com",
        team: "Code Wizards",
        country: "Iran",
        status: "Inactive"
    }, 
    {
        id: 11,
        title: "Floyd Miles",
        phone_no: "(205) 555-0100",
        email: "floyd@yahoo.com",
        team: "Byte Builders",
        country: "Kiribati",
        status: "Active"
    },
    {
        id: 12,
        title: "Ronald Richards",
        phone_no: "(302) 555-0107",
        email: "ronald@adobe.com",
        team: "Algo Masters",
        country: "Israel",
        status: "Inactive"
    },
    {
        id: 13,
        title: "Marvin McKinney",
        phone_no: "(252) 555-0126",
        email: "marvin@tesla.com",
        team: "Code Wizards",
        country: "Iran",
        status: "Inactive"
    },   
]