export const Submission = [
    {
        id: 1,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Rejected",
        date: "May 15, 2025",
    },
    {
        id: 2,
        title: "Neural Network Visualizer",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Reviewed",
        date: "May 16, 2025",
    },
    {
        id: 3,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "4",
        team: "Tech Titans",
        status: "Pending",
        date: "May 17, 2025",
    },
    {
        id: 4,
        title: "Sustainable Energy Monitor",
        categoty: "AI Innovation challege",
        members: "5",
        team: "Code Warriors",
        status: "Rejected",
        date: "May 18, 2025",
    },
    {
        id: 5,
        title: "Voice Recognition API",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Reviewed",
        date: "May 19, 2025",
    },
    {
        id: 6,
        title: "AI-Powered Chatbot",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Pending",
        date: "May 20, 2025",
    },
    {
        id: 7,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "4",
        team: "Tech Titans",
        status: "Rejected",
        date: "May 21, 2025",
    },
    {
        id: 8,
        title: "Sustainable Energy Monitor",
        categoty: "AI Innovation challege",
        members: "5",
        team: "Code Warriors",
        status: "Reviewed",
        date: "May 22, 2025",
    },
    {
        id: 9,
        title: "Voice Recognition API",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Pending",
        date: "May 23, 2025",
    },
    {
        id: 10,
        title: "AI-Powered Chatbot",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Rejected",
        date: "May 24, 2025",
    },
    {
        id: 11,
        title: "Sustainable Energy Monitor",
        categoty: "AI Innovation challege",
        members: "5",
        team: "Code Warriors",
        status: "Reviewed",
        date: "May 22, 2025",
    },
    {
        id: 12,
        title: "Neural Network Visualizer",
        categoty: "AI Innovation challege",
        members: "3",
        team: "Code Ninjas",
        status: "Reviewed",
        date: "May 16, 2025",
    }, 
    {
        id: 13,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Rejected",
        date: "May 15, 2025",
    },
    {
        id: 14,
        title: "Voice Recognition API",
        categoty: "AI Innovation challege",
        members: "2",
        team: "Tech Wizards",
        status: "Pending",
        date: "May 23, 2025",
    },
    {
        id: 15,
        title: "SmartAI Assistant",
        categoty: "AI Innovation challege",
        members: "4",
        team: "Tech Titans",
        status: "Pending",
        date: "May 17, 2025",
    },

]