import Image from "next/image";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import OTP from "../public/OTP.jpg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-[95vh] flex-wrap content-center items-center justify-center py-5">
          <div className="relative flex-wrap justify-between md:flex">
            <Image
              src={OTP}
              className="xs:p-0 object-contain p-16"
              alt="Logo"
            />
            <div className="relative sm:min-w-full md:min-w-[30rem]">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
