"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation"; // Import usePathname
import Navbar from "./components/Navbar/page";
import Hackathon_Navbar from "./components/Hackathon_Navbar/page";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get current route
  const isHackathonRoute = pathname.startsWith("/pages/hackathon");


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Conditionally render navbar based on pathname */}
        {isHackathonRoute ? <Hackathon_Navbar /> : <Navbar />}
        {children}
      </body>
    </html>
  );
}


